[package]
name = "aoc2015day03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-util = { path = "../../../util" }

itertools.workspace = true
eyre.workspace = true
glam.workspace = true
