[package]
name = "aoc2023day03"
version.workspace = true
edition.workspace = true

[dependencies]
aoc-util.workspace = true
eyre.workspace = true

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "aoc2023day03-bench"
path = "benches/benchmarks.rs"
harness = false
